global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'isekai-gateway'
    environment: 'docker'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the API Gateway
  - job_name: 'isekai-gateway'
    scrape_interval: 10s
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'isekai-gateway'

  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8888']
      - targets: ['otel-collector:8889']

  # Scrape Jaeger metrics
  - job_name: 'jaeger'
    scrape_interval: 10s
    static_configs:
      - targets: ['jaeger:14269']
